"""add unique recovery case transaction

Revision ID: 567796f36585
Revises: 3611f06e497a
Create Date: 2026-08-29 23:58:31.676615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567796f36585'
down_revision: Union[str, Sequence[str], None] = '3611f06e497a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recovery_case_transaction', 'recovery_cases', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recovery_case_transaction', 'recovery_cases', type_='unique')
    # ### end Alembic commands ###
