"""add recovery ground truth

Revision ID: 3611f06e497a
Revises: 03d9ef324132
Create Date: 2026-08-28 14:49:40.950974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3611f06e497a'
down_revision: Union[str, Sequence[str], None] = '03d9ef324132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_ground_truth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('recoverable', sa.Boolean(), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('simulated_outcome', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_ground_truth')
    # ### end Alembic commands ###
